import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Welcome to Next.js & Tailwind running on Brev.dev
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://brev.dev/docs" className={styles.card}>
            <h2>Brev.dev Documentation &rarr;</h2>
            <p>Use Brev.dev to keep your environment working properly.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>NextJS Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/brev.svg" alt="Brev.dev" width={108} height={72} />
          </span>
        </a>
      </footer>
    </div>
  )
}
